import {Dimensions, StyleSheet} from 'react-native';
import {ViewScale} from '../../config/ViewScale';
const {width, height} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    width: width * 0.9,
    backgroundColor: '#1D1D1D',
    marginTop: ViewScale(80),
    alignSelf: 'center',
    paddingVertical: ViewScale(20),
  },
  head: {
    position: 'absolute',
    top: ViewScale(height * -0.12),
    left: 0,
    width: 0,
    height: 0,
    borderStyle: 'solid',
    borderLeftWidth: width * 0.45,
    borderLeftColor: 'transparent',
    borderRightWidth: width * 0.45,
    borderRightColor: 'transparent',
    borderBottomWidth: width * 0.225,
    borderBottomColor: '#1D1D1D',
    alignSelf: 'center',
  },
  bar: {
    position: 'absolute',
    bottom: ViewScale(height * -0.12),
    left: 0,
    width: 0,
    height: 0,
    borderStyle: 'solid',
    borderLeftWidth: width * 0.45,
    borderLeftColor: 'transparent',
    borderRightWidth: width * 0.45,
    borderRightColor: 'transparent',
    borderTopWidth: width * 0.225,
    borderTopColor: '#1D1D1D',
    alignSelf: 'center',
  },
  logob: {
    width: ViewScale(30),
    height: ViewScale(10),
    alignSelf: 'center',
    marginTop: ViewScale(20),
  },
  logob1: {
    width: ViewScale(10),
    height: ViewScale(10),
    alignSelf: 'center',
    position: 'absolute',
    marginTop: ViewScale(-50),
  },
  imgjew: {
    width: width * 0.5,
    height: ViewScale(250),
    alignSelf: 'center',
    marginTop: ViewScale(-10),
  },
  imgsa: {
    width: width * 0.82,
    height: ViewScale(150),
    alignSelf: 'center',
    marginTop: ViewScale(-10),
  },
  textHeader: {
    fontSize: ViewScale(24),
    color: '#DAA560',
    alignSelf: 'center',
    marginTop: ViewScale(20),
    fontFamily: 'Cantoria MT Std',
  },
  textsuphead: {
    fontSize: ViewScale(22),
    color: '#DAA560',
    textAlign: 'center',
    marginTop: ViewScale(20),
    fontFamily: 'Cantoria MT Std',
  },
  textdetail: {
    fontSize: ViewScale(18),
    color: '#DAA560',
    width: width * 0.8,
    alignSelf: 'center',
    marginTop: ViewScale(10),
    fontFamily: 'Cantoria MT Std',
  },
  view: {
    flexDirection: 'row',
    width: width * 0.8,
    justifyContent: 'space-between',
    marginVertical: ViewScale(10),
    alignSelf: 'center',
  },
  button: {
    borderBottomWidth: 1,
    borderBottomColor: '#DAA560',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  textbutton: {
    color: '#DAA560',
    fontSize: ViewScale(18),
    alignSelf: 'center',
    fontFamily: 'Cantoria MT Std',
  },
  logoditp: {
    width: ViewScale(70),
    height: ViewScale(30),
    alignSelf: 'center',
    marginRight: ViewScale(10),
  },
  logo100: {
    width: ViewScale(60),
    height: ViewScale(30),
    alignSelf: 'center',
  },
  row: {
    flexDirection: 'row',
    alignSelf: 'center',
  },
  textalin: {
    textAlign: 'center',
    fontSize: ViewScale(18),
    color: '#DAA5ViewScale(60)',
    width: width * 0.75,
    alignSelf: 'center',
    marginTop: ViewScale(30),
    marginBottom: ViewScale(20),
    fontFamily: 'Cantoria MT Std',
  },
  review: {
    height: ViewScale(60),
    borderRightWidth: 1,
    borderRightColor: '#DAA560',
    width: width * 0.267,
    paddingHorizontal: 5,
  },
  review1: {
    height: ViewScale(60),
    width: width * 0.267,
    paddingHorizontal: 5,
  },
  textnumber: {
    fontSize: ViewScale(26),
    color: '#fff',
    alignSelf: 'center',
    fontFamily: 'Cantoria MT Std',
  },
  textsup: {
    fontSize: ViewScale(17),
    color: '#fff',
    fontFamily: 'Cantoria MT Std',
    textAlign: 'center',
  },
  imgpat: {
    width: width * 0.75,
    alignSelf: 'center',
    height: ViewScale(250),
    marginVertical: ViewScale(20),
  },
});
export default styles;
