import {Dimensions, StyleSheet} from 'react-native';
const {width, height} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    width: width * 0.9,
    backgroundColor: '#1D1D1D',
    marginTop: 80,
    alignSelf: 'center',
    paddingVertical: 20,
  },
  head: {
    position: 'absolute',
    top: height * -0.103,
    left: 0,
    width: 0,
    height: 0,
    borderStyle: 'solid',
    borderLeftWidth: width * 0.45,
    borderLeftColor: 'transparent',
    borderRightWidth: width * 0.45,
    borderRightColor: 'transparent',
    borderBottomWidth: width * 0.225,
    borderBottomColor: '#1D1D1D',
    alignSelf: 'center',
  },
  bar: {
    position: 'absolute',
    bottom: height * -0.103,
    left: 0,
    width: 0,
    height: 0,
    borderStyle: 'solid',
    borderLeftWidth: width * 0.45,
    borderLeftColor: 'transparent',
    borderRightWidth: width * 0.45,
    borderRightColor: 'transparent',
    borderTopWidth: width * 0.225,
    borderTopColor: '#1D1D1D',
    alignSelf: 'center',
  },
  logob: {
    width: 30,
    height: 10,
    alignSelf: 'center',
    marginTop: 20,
  },
  logob1: {
    width: 10,
    height: 10,
    alignSelf: 'center',
    position: 'absolute',
    marginTop: -50,
  },
  imgjew: {
    width: width * 0.5,
    height: 200,
    alignSelf: 'center',
    marginTop: -20,
  },
  imgsa: {
    width: width * 0.75,
    height: 100,
    alignSelf: 'center',
    marginTop: -20,
  },
  textHeader: {
    fontSize: 22,
    color: '#DAA560',
    alignSelf: 'center',
    marginTop: 20,
    fontFamily: 'Cantoria MT Std',
  },
  textsuphead: {
    fontSize: 20,
    color: '#DAA560',
    textAlign: 'center',
    marginTop: 20,
    fontFamily: 'Cantoria MT Std',
  },
  textdetail: {
    fontSize: 16,
    color: '#DAA560',
    width: width * 0.8,
    alignSelf: 'center',
    marginTop: 10,
    fontFamily: 'Cantoria MT Std',
  },
  view: {
    flexDirection: 'row',
    width: width * 0.8,
    justifyContent: 'space-between',
    marginVertical: 10,
    alignSelf: 'center',
  },
  button: {
    borderBottomWidth: 1,
    borderBottomColor: '#DAA560',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  textbutton: {
    color: '#DAA560',
    fontSize: 16,
    alignSelf: 'center',
    fontFamily: 'Cantoria MT Std',
  },
  logoditp: {
    width: 70,
    height: 30,
    alignSelf: 'center',
    marginRight: 10,
  },
  logo100: {
    width: 60,
    height: 30,
    alignSelf: 'center',
  },
  row: {
    flexDirection: 'row',
    alignSelf: 'center',
  },
  textalin: {
    textAlign: 'center',
    fontSize: 16,
    color: '#DAA560',
    width: width * 0.75,
    alignSelf: 'center',
    marginTop: 30,
    marginBottom: 20,
    fontFamily: 'Cantoria MT Std',
  },
  review: {
    height: 60,
    borderRightWidth: 1,
    borderRightColor: '#DAA560',
    width: width * 0.267,
    paddingHorizontal: 5,
  },
  review1: {
    height: 60,
    width: width * 0.267,
    paddingHorizontal: 5,
  },
  textnumber: {
    fontSize: 24,
    color: '#fff',
    alignSelf: 'center',
    fontFamily: 'Cantoria MT Std',
  },
  textsup: {
    fontSize: 15,
    color: '#fff',
    fontFamily: 'Cantoria MT Std',
    textAlign: 'center',
  },
  imgpat: {
    width: width * 0.75,
    alignSelf: 'center',
    height: 250,
    marginVertical: 20,
  },
});
export default styles;
