import {Dimensions, StyleSheet} from 'react-native';
import {ViewScale} from '../../config/ViewScale';
const {width, height} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    width: width,
    height: height,
    backgroundColor: '#000',
  },
  viewinput: {
    width: width,
    backgroundColor: '#343434',
    justifyContent: 'center',
    paddingVertical: ViewScale(30),
  },
  input: {
    width: width * 0.88,
    height: ViewScale(50),
    backgroundColor: '#F7F7F7',
    borderRadius: ViewScale(4),
    alignSelf: 'center',
    paddingLeft: ViewScale(20),
    fontSize: ViewScale(20),
    borderColor: '#EEECE2',
    borderWidth: 1,
    marginBottom: ViewScale(20),
    fontFamily: 'Cantoria MT Std',
  },
  input1: {
    width: width * 0.88,
    height: ViewScale(120),
    backgroundColor: '#F7F7F7',
    borderRadius: ViewScale(4),
    alignSelf: 'center',
    paddingHorizontal: ViewScale(20),
    fontSize: ViewScale(20),
    borderColor: '#EEECE2',
    borderWidth: 1,
    marginBottom: ViewScale(20),
    fontFamily: 'Cantoria MT Std',
    paddingTop: ViewScale(10),
  },
  botton: {
    width: width * 0.88,
    height: ViewScale(50),
    borderRadius: ViewScale(4),
    alignSelf: 'center',
    borderColor: '#DAA560',
    borderWidth: 1,
    marginTop: ViewScale(20),
    justifyContent: 'center',
    marginBottom: ViewScale(20),
  },
  textbotton: {
    fontFamily: 'Cantoria MT Std',
    fontSize: ViewScale(22),
    color: '#DAA560',
    alignSelf: 'center',
  },
  viewtags: {
    backgroundColor: '#000',
    paddingVertical: ViewScale(50),
    paddingHorizontal: ViewScale(20),
    justifyContent: 'center',
  },
  textags: {
    fontFamily: 'Cantoria MT Std',
    fontSize: ViewScale(20),
    color: '#fff',
    alignSelf: 'center',
    letterSpacing: 0.2,
  },
  textags1: {
    fontFamily: 'Cantoria MT Std',
    fontSize: ViewScale(20),
    color: '#fff',
    alignSelf: 'center',
    letterSpacing: 0.1,
    width: width * 0.7,
  },
  rowtags: {
    flexDirection: 'row',
    width: width * 0.88,
    alignSelf: 'center',
    marginTop: ViewScale(15),
  },
  icon: {
    width: ViewScale(20),
    height: ViewScale(20),
    alignSelf: 'center',
    marginRight: ViewScale(30),
  },
  containermodal: {
    width: width,
    height: height,
    backgroundColor: '#707070bb',
    justifyContent: 'center',
  },
  viewmodal: {
    width: width * 0.96,
    backgroundColor: '#EEECE2',
    alignSelf: 'center',
    borderRadius: ViewScale(12),
    paddingHorizontal: ViewScale(15),
    paddingVertical: ViewScale(25),
  },
  iconmodal: {
    alignSelf: 'flex-end',
  },
  texttopicmodal: {
    fontSize: ViewScale(24),
    color: '#000',
    alignSelf: 'center',
    marginBottom: ViewScale(10),
    fontFamily: 'Cantoria MT Std',
    marginTop: ViewScale(10),
  },
  icon1: {
    alignSelf: 'center',
    marginBottom: ViewScale(10),
  },
  buttonsec: {
    backgroundColor: '#EEECE2',
    width: width * 0.5,
    alignSelf: 'center',
    marginTop: ViewScale(20),
    height: ViewScale(48),
    borderRadius: ViewScale(2),
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#DAA560',
  },
  textsec: {
    fontSize: ViewScale(24),
    color: '#DAA560',
    alignSelf: 'center',
    fontFamily: 'Cantoria MT Std',
  },
  textt: {
    fontFamily: 'Cantoria MT Std',
    fontSize: ViewScale(22),
    color: '#DAA560',
    letterSpacing: 0.1,
    marginBottom: ViewScale(10),
  },
});

export default styles;
