import {Dimensions, StyleSheet} from 'react-native';
const {width, height} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    width: width,
    height: height,
  },
  viewrow: {
    flexDirection: 'row',
    width: width,
    justifyContent: 'space-between',
    alignSelf: 'center',
    paddingHorizontal: 20,
    marginVertical: 20,
  },
  viewrow1: {
    flexDirection: 'row',
    width: width * 0.5,
    justifyContent: 'space-between',
    alignSelf: 'center',
  },
  texthead: {
    fontSize: 15,
    fontFamily: 'Cantoria MT Std',
    color: '#646363',
    alignSelf: 'center',
  },
  textdelete: {
    fontSize: 15,
    fontFamily: 'Cantoria MT Std',
    color: '#D76060',
    alignSelf: 'center',
  },
  row: {
    flexDirection: 'row',
  },
  viewlist: {
    width: 25,
    height: 25,
    borderWidth: 2,
    borderColor: '#888888',
    marginRight: 20,
    alignSelf: 'center',
    position: 'relative',
  },
  iconpust: {
    width: 18,
    height: 18,
    alignSelf: 'center',
    marginRight: 5,
    marginTop: -3,
  },
  textlist: {
    fontSize: 20,
    fontFamily: 'Cantoria MT Std',
    color: '#646363',
    alignSelf: 'center',
  },
  viewflat: {
    width: width * 0.5,
    justifyContent: 'center',
    height: 200,
    marginBottom: 10,
  },
  rowflat: {
    flexDirection: 'row',
    width: width * 0.45,
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingTop: 10,
  },
  img: {
    width: width * 0.45,
    height: 150,
    alignSelf: 'center',
    marginTop: 10,
    borderRadius: 10,
  },
  textflat: {
    textAlign: 'center',
    fontSize: 15,
    fontFamily: 'Cantoria MT Std',
    marginTop: 10,
    width: width * 0.4,
  },
  texttt: {
    height: 60,
    width: width * 0.35,
    alignSelf: 'center',
  },
  buttonlist: {
    borderWidth: 1,
    borderRadius: 12.5,
    justifyContent: 'center',
    width: 25,
    height: 25,
  },
  containersort: {
    flex: 1,
    padding: 20,
  },
  viewsort: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: width * 0.9,
    alignSelf: 'center',
  },
  textsort: {
    fontSize: 20,
    alignSelf: 'center',
    marginVertical: 15,
    fontFamily: 'Cantoria MT Std',
  },
  textsorthead: {
    fontSize: 16,
    fontFamily: 'Cantoria MT Std',
    color: '#444444',
    marginBottom: 25,
  },
  bottomsort: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#444',
    marginRight: 15,
  },
  textlist1: {
    fontSize: 24,
    fontFamily: 'Cantoria MT Std',
    color: '#646363',
  },
  row3: {
    flexDirection: 'row',
    borderBottomColor: '#88888860',
    paddingRight: 20,
    justifyContent: 'space-between',
    width: width * 0.9,
    marginBottom: 5,
  },
  linersort: {
    width: width * 0.85,
    alignSelf: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#444',
    marginVertical: 15,
  },
  add: {
    height: 80,
    paddingBottom: 20,
    paddingHorizontal: 20,
  },
  containermodal: {
    width: width,
    height: height,
    backgroundColor: '#707070bb',
    justifyContent: 'center',
  },
  viewmodal: {
    width: width * 0.96,
    backgroundColor: '#EEECE2',
    alignSelf: 'center',
    borderRadius: 12,
    paddingHorizontal: 15,
    paddingTop: 25,
    paddingBottom: 35,
  },
  iconmodal: {
    alignSelf: 'flex-end',
  },
  textopmodal: {
    fontSize: 22,
    color: '#646363',
    textAlign: 'center',
    fontFamily: 'Cantoria MT Std',
    marginBottom: 20,
  },
  viewinput: {
    width: width * 0.85,
    height: 50,
    borderRadius: 4,
    backgroundColor: '#fff',
    justifyContent: 'center',
    marginBottom: 20,
    alignSelf: 'center',
  },
  input: {
    width: width * 0.78,
    alignSelf: 'center',
    fontSize: 18,
    fontFamily: 'Cantoria MT Std',
    color: '#646363',
  },
  touchedit: {
    width: width * 0.85,
    height: 50,
    borderWidth: 1,
    borderRadius: 4,
    borderColor: '#DAA560',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  textedit: {
    fontSize: 22,
    color: '#DAA560',
    fontFamily: 'Cantoria MT Std',
    alignSelf: 'center',
    marginTop: 5,
  },
});

export default styles;
