import {Dimensions, StyleSheet} from 'react-native';
const {width, height} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    width: width,
    height: height,
  },
  viewHeader: {
    backgroundColor: '#EEECE2',
    width: width,
    paddingHorizontal: 20,
    paddingBottom: 20,
    justifyContent: 'center',
    position: 'relative',
  },
  logo: {
    width: 80,
    height: 80,
    alignSelf: 'center',
    marginTop: -20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 2,
    borderRadius: 45,
    borderWidth: 0.5,
    borderColor: '#fff',
  },
  textTopic: {
    fontSize: 18,
    color: '#DAA560',
    alignSelf: 'center',
    marginTop: 10,
    width: width * 0.75,
    textAlign: 'center',
    fontFamily: 'Cantoria MT Std',
  },
  texthead: {
    fontSize: 14,
    color: '#000',
    alignSelf: 'center',
    marginTop: 10,
    fontFamily: 'Cantoria MT Std',
  },
  textloca: {
    fontSize: 10,
    color: '#000',
    alignSelf: 'center',
    marginLeft: 5,
    fontFamily: 'Cantoria MT Std',
  },
  row: {
    flexDirection: 'row',
    alignSelf: 'center',
    marginTop: 5,

    justifyContent: 'space-between',
  },
  button: {
    borderWidth: 1,
    borderColor: '#DAA560',
    height: 35,
    width: width * 0.35,
    marginHorizontal: 3,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  textbutton: {
    fontSize: 14,
    color: '#DAA560',
    alignSelf: 'center',
    fontFamily: 'Cantoria MT Std',
  },
  page: {
    marginHorizontal: 10,
    marginTop: 15,
  },
  textpage: {
    alignSelf: 'center',
    fontFamily: 'Cantoria MT Std',
  },
  containerproduct: {
    width: width,
  },
  viewproduct: {
    width: width * 0.8,
    height: 260,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 9,
    backgroundColor: '#fff',
    marginTop: 20,
    alignSelf: 'center',
  },
  viewlist: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 10,
    marginRight: 10,
  },
  buttonlist: {
    borderWidth: 1,
    borderRadius: 12.5,
    justifyContent: 'center',
    width: 25,
    height: 25,
  },
  imgtopic: {
    width: width * 0.6,
    height: 180,
    alignSelf: 'center',
    marginTop: 10,
  },
  texttoproduct: {
    fontSize: 20,
    color: '#000000',
    marginTop: 20,
    textAlign: 'center',
    fontWeight: '600',
    fontFamily: 'Cantoria MT Std',
    width: width * 0.85,
    alignSelf: 'center',
  },
  textdetailproduct: {
    fontSize: 16,
    color: '#ABABAB',
    textAlign: 'center',
    paddingHorizontal: 40,
    alignSelf: 'center',
    marginTop: 10,
    fontFamily: 'Cantoria MT Std',
  },
  minibutton: {
    height: 30,
    backgroundColor: '#DEDDD4',
    borderRadius: 4,
    justifyContent: 'center',
    alignSelf: 'center',
    marginHorizontal: 3,
    paddingHorizontal: 5,
    marginVertical: 10,
  },
  minitext: {
    fontSize: 10,
    color: '#000',
    fontFamily: 'Cantoria MT Std',
    alignSelf: 'center',
  },
  buttonflat: {
    backgroundColor: '#fff',
    width: width * 0.42,
    height: 150,
    alignSelf: 'center',
    marginTop: 20,
    borderRadius: 5,
    marginLeft: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 11,
  },
  imgflat: {
    width: width * 0.42,
    height: 120,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    alignSelf: 'center',
  },
  textflat: {
    fontSize: 10,
    color: '#000',
    marginLeft: 10,
    alignSelf: 'center',
    fontFamily: 'Cantoria MT Std',
    paddingHorizontal: 10,
    marginTop: 5,
    textAlign: 'center',
  },
  containerabout: {
    width: width,
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  textdetailabout: {
    fontSize: 16,
    color: '#000',

    marginBottom: 20,
    fontFamily: 'Cantoria MT Std',
    marginTop: 10,
  },
  textsupabout: {
    fontSize: 16,
    color: '#DAA560',
    fontWeight: '800',
    width: width * 0.45,
    fontFamily: 'Cantoria MT Std',
  },
  listsocial: {
    borderWidth: 1,
    borderRadius: 20,
    justifyContent: 'center',
    width: 40,
    height: 40,
    borderColor: '#DAA560',
    marginRight: 10,
  },
  rowsocial: {
    flexDirection: 'row',
    marginTop: 15,
  },
  buttondowload: {
    width: width * 0.9,
    height: 60,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 2,
    backgroundColor: '#FAFAFA',
    alignSelf: 'center',
    marginTop: 20,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 50,
  },
  textconten: {
    fontSize: 13,
    color: '#000',
    fontFamily: 'Cantoria MT Std',

    width: width * 0.47,
  },
  liner: {
    width: width * 1,
    borderBottomColor: '#DAA560',
    borderBottomWidth: 1,
    alignSelf: 'center',
    marginVertical: 20,
  },
  vedio: {
    width: 18,
    height: 11,
    alignSelf: 'center',
    marginRight: 10,
  },
  containermodal: {
    width: width,
    height: height,
    backgroundColor: '#707070bb',
    justifyContent: 'center',
  },
  viewmodal: {
    width: width * 0.96,
    backgroundColor: '#EEECE2',
    alignSelf: 'center',
    borderRadius: 12,
    paddingHorizontal: 15,
    paddingTop: 25,
    paddingBottom: 35,
  },
  iconmodal: {
    alignSelf: 'flex-end',
  },
  textopmodal: {
    fontSize: 22,
    color: '#646363',
    textAlign: 'center',
    fontFamily: 'Cantoria MT Std',
    marginBottom: 20,
  },
  viewinput: {
    width: width * 0.85,
    height: 50,
    borderRadius: 4,
    backgroundColor: '#fff',
    justifyContent: 'center',
    marginBottom: 20,
    alignSelf: 'center',
  },
  viewinput1: {
    width: width * 0.85,
    height: 120,
    borderRadius: 4,
    backgroundColor: '#fff',

    marginBottom: 20,
    alignSelf: 'center',
    paddingTop: 10,
  },
  input: {
    width: width * 0.78,
    alignSelf: 'center',
    fontSize: 18,
    fontFamily: 'Cantoria MT Std',
    color: '#646363',
  },
  touchedit: {
    width: width * 0.85,
    height: 50,
    borderWidth: 1,
    borderRadius: 4,
    borderColor: '#DAA560',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  textedit: {
    fontSize: 24,
    color: '#DAA560',
    fontFamily: 'Cantoria MT Std',
    alignSelf: 'center',
    marginTop: 5,
  },
  picker: {
    placeholder: {
      color: '#AFAFAF',
      padding: 0,
      marginTop: 5,
      fontSize: 18,
      paddingLeft: 15,
    },
    inputIOS: {
      color: '#646363',

      paddingRight: 30,
      fontSize: 18,
    },
    inputAndroid: {
      color: '#646363',
      padding: 0,
      margin: 0,
      fontSize: 18,
      paddingRight: 30,
    },
    iconContainer: {
      right: 0,
    },
  },
  containersort: {
    flex: 1,
    padding: 20,
  },
  viewsort: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: width * 0.9,
    alignSelf: 'center',
  },
  textsort: {
    fontSize: 20,
    alignSelf: 'center',
    marginVertical: 15,
    fontFamily: 'Cantoria MT Std',
  },
  textsorthead: {
    fontSize: 16,
    fontFamily: 'Cantoria MT Std',
    color: '#444444',
    marginBottom: 25,
  },
  bottomsort: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#444',
    marginRight: 15,
  },
  textlist1: {
    fontSize: 24,
    fontFamily: 'Cantoria MT Std',
    color: '#646363',
  },
  row3: {
    flexDirection: 'row',
    borderBottomColor: '#88888860',
    paddingRight: 20,
    justifyContent: 'space-between',
    width: width * 0.9,
    marginBottom: 5,
  },
  linersort: {
    width: width * 0.85,
    alignSelf: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#444',
    marginVertical: 15,
  },
  add: {
    height: 80,
    paddingBottom: 20,
    paddingHorizontal: 20,
  },
  row5: {
    flexDirection: 'row',
  },
  iconpust: {
    width: 18,
    height: 18,
    alignSelf: 'center',
    marginRight: 5,
    marginTop: -3,
  },

  viewmodal: {
    width: width * 0.96,
    backgroundColor: '#EEECE2',
    alignSelf: 'center',
    borderRadius: 12,
    paddingHorizontal: 15,
    paddingTop: 25,
    paddingBottom: 35,
  },
  iconmodal: {
    alignSelf: 'flex-end',
  },
  texttopicmodal: {
    fontSize: 22,
    color: '#646363',
    alignSelf: 'center',
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'Cantoria MT Std',
  },
  textdetailmodal: {
    fontSize: 18,
    color: '#646363',
    alignSelf: 'center',
    textAlign: 'center',
    fontFamily: 'Cantoria MT Std',
  },
  textemaillmodal: {
    fontSize: 18,
    color: '#DAA560',
    alignSelf: 'center',
    textAlign: 'center',
    marginVertical: 5,
    fontFamily: 'Cantoria MT Std',
  },
  buttonexhi: {
    backgroundColor: '#EEECE2',
    width: width * 0.8,
    alignSelf: 'center',
    marginTop: 20,
    height: 48,
    borderRadius: 2,
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#DAA560',
    flexDirection: 'row',
    paddingHorizontal: 25,
  },
  textexhi: {
    fontSize: 20,
    color: '#DAA560',
    alignSelf: 'center',
    fontFamily: 'Cantoria MT Std',
  },
});

export default styles;
