export {default as Home} from './Home/Home';
export {default as About} from './About/About';
export {default as Exhibitors} from './Exhibitors/Exhibitors';
export {default as Event} from './Event/Event';
export {default as News} from './News/News';
export {default as Login} from './Login/Login';
export {default as Hightligth} from './Hightligth/Hightligth';
export {default as ExhibitorsDetail} from './ExhibitorsDetail/ExhibitorsDetail';
export {default as Splash} from './Splash/Splash';
