import {Dimensions, Platform, StyleSheet} from 'react-native';
import {ViewScale} from '../../config/ViewScale';
const {width, height} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    width: width,
    height: height,
  },
  viewsearch: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: ViewScale(15),
    width: width * 0.9,
    alignSelf: 'center',
    marginLeft: ViewScale(10),
  },
  viewinsearch: {
    flexDirection: 'row',
    width: width * 0.8,
    backgroundColor: '#fff',
    borderRadius: ViewScale(8),
  },
  icon1: {
    alignSelf: 'center',
    marginLeft: ViewScale(10),
    zIndex: 99,
  },
  input: {
    width: ViewScale(270),
    height: Platform.OS === 'ios' ? ViewScale(35) : ViewScale(45),
    marginLeft: ViewScale(10),
    borderRadius: ViewScale(8),
    fontSize: ViewScale(16),
    color: '#888888',
    fontFamily: 'Cantoria MT Std',
  },
  iconsea: {
    width: ViewScale(30),
    height: ViewScale(30),
    alignSelf: 'center',
  },
  buttonflat: {
    backgroundColor: '#fff',
    width: width * 0.45,
    height: ViewScale(190),
    alignSelf: 'center',
    marginTop: ViewScale(20),
    borderRadius: ViewScale(5),
    marginLeft: ViewScale(15),
    shadowColor: '#00000029',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.43,
    shadowRadius: 9.51,
    elevation: ViewScale(15),
  },
  imgflat: {
    width: width * 0.45,
    height: ViewScale(150),
    borderTopLeftRadius: ViewScale(5),
    borderTopRightRadius: ViewScale(5),
    borderBottomWidth: 0.5,
    borderBottomColor: '#33333ViewScale(35)0',
  },
  text: {
    fontSize: ViewScale(16),
    fontFamily: 'Cantoria MT Std',
    color: '#646363',
    alignSelf: 'center',
    marginLeft: ViewScale(10),
  },
  FloatingActionButtonStyle: {
    position: 'absolute',
    width: ViewScale(40),
    height: ViewScale(40),
    backgroundColor: '#fff',
    transform: [{rotate: '45deg'}],
    alignItems: 'center',
    justifyContent: 'center',
    right: ViewScale(30),
    bottom: ViewScale(30),
    borderColor: '#000000',
    shadowColor: '#00000029',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.43,
    shadowRadius: 9.51,
    elevation: ViewScale(15),
  },
  tags: {
    width: width,
    borderBottomWidth: 1,
    borderBottomColor: '#DAA560',

    paddingVertical: ViewScale(20),
  },
  texttags: {
    fontSize: ViewScale(16),
    color: '#646363',
    fontFamily: 'Cantoria MT Std',
    marginLeft: ViewScale(20),
  },
  roww: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: width * 0.9,
    marginBottom: ViewScale(10),
  },
  icon: {
    alignSelf: 'center',
  },
  row: {
    flexDirection: 'row',
    width: width * 0.42,
    paddingHorizontal: ViewScale(5),
    alignSelf: 'center',
    height: ViewScale(30),
  },
  imglogo: {
    width: ViewScale(20),
    height: ViewScale(20),
    alignSelf: 'center',
    borderRadius: ViewScale(10),
    borderColor: '#444',
    borderWidth: 0.1,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.43,
    shadowRadius: 9.51,
    elevation: ViewScale(15),
  },
  containersort: {
    flex: 1,
    padding: ViewScale(20),
  },
  viewsort: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: width * 0.9,
    alignSelf: 'center',
  },
  textsort: {
    fontSize: ViewScale(22),
    alignSelf: 'center',
    marginLeft: ViewScale(20),
    fontFamily: 'Cantoria MT Std',
  },
  textsorthead: {
    fontSize: ViewScale(18),
    fontFamily: 'Cantoria MT Std',
    color: '#444444',
  },
  bottomsort: {
    width: ViewScale(20),
    height: ViewScale(20),
    borderRadius: ViewScale(10),
    borderWidth: 1,
    borderColor: '#444',
    marginRight: ViewScale(15),
  },
  textsortdetail: {
    fontSize: ViewScale(18),
    fontFamily: 'Cantoria MT Std',
    color: '#000',
    alignSelf: 'center',
  },
  linersort: {
    width: width * 0.85,
    alignSelf: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#444',
    marginVertical: ViewScale(15),
  },
  bottontags: {
    width: width * 0.4,
    height: ViewScale(40),
    borderWidth: 1,
    borderColor: '#44444450',
    justifyContent: 'center',
    marginTop: ViewScale(10),
    borderRadius: ViewScale(10),
  },
  rowbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: width * 0.85,
    alignSelf: 'center',
    marginVertical: ViewScale(20),
  },
  touch: {
    width: width * 0.4,
    height: ViewScale(35),
    borderColor: '#DAA560',
    borderWidth: 1,
    borderRadius: 4,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  textouch: {
    fontSize: ViewScale(20),
    fontFamily: 'Cantoria MT Std',
    color: '#DAA560',
    alignSelf: 'center',
  },
});

export default styles;
