import {Dimensions, StyleSheet} from 'react-native';
import {ViewScale} from '../../config/ViewScale';
const {width, height} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    width: width,
    height: height,
  },
  buttonflat: {
    width: width,
    height: ViewScale(210),
    marginBottom: ViewScale(5),
  },
  linear: {
    width: width,
    height: ViewScale(210),
    zIndex: 99,
    justifyContent: 'flex-end',
    paddingLeft: ViewScale(10),
    paddingBottom: ViewScale(5),
  },
  containerview: {
    // height: height,
    width: width,
    backgroundColor: '#000000',
  },
  text: {
    fontSize: ViewScale(20),
    color: '#FFFFFF',
    fontFamily: 'Cantoria MT Std',
  },
  row: {
    flexDirection: 'row',
    alignSelf: 'center',
    width: width * 0.7,
    justifyContent: 'space-between',
    marginTop: ViewScale(20),
    marginBottom: ViewScale(70),
  },
  button: {
    width: width * 0.3,
    height: ViewScale(42),
    borderWidth: 1,
    borderColor: '#DAA560',
    borderRadius: ViewScale(2),
    justifyContent: 'center',
  },
  textbotton: {
    fontSize: ViewScale(18),
    color: '#DAA560',
    fontFamily: 'Cantoria MT Std',
    alignSelf: 'center',
  },
  dimon: {
    width: ViewScale(40),
    height: ViewScale(40),
    backgroundColor: '#fff',
    transform: [{rotate: '45deg'}],
    alignSelf: 'flex-end',
    marginTop: -ViewScale(20),
    marginRight: ViewScale(30),
    justifyContent: 'center',
    shadowColor: '#00000029',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.43,
    shadowRadius: 9.51,
    elevation: 15,
  },
  icon: {
    alignSelf: 'center',
  },
  input: {
    width: width * 0.9,
    height: ViewScale(35),
    border: 1,
    backgroundColor: '#fff',
    paddingLeft: ViewScale(35),
    borderRadius: ViewScale(8),
    fontSize: ViewScale(16),
    color: '#888888',
    fontFamily: 'Cantoria MT Std',
    alignSelf: 'center',
  },

  viewsearch: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: ViewScale(15),
    width: width * 0.9,
    alignSelf: 'center',
    marginLeft: ViewScale(10),
  },
  viewinsearch: {
    flexDirection: 'row',
    width: width * 0.8,
    backgroundColor: '#fff',
    borderRadius: ViewScale(8),
  },
  icon1: {
    alignSelf: 'center',
    marginLeft: ViewScale(10),
    zIndex: 99,
  },
  input: {
    width: ViewScale(270),
    height: ViewScale(35),
    marginLeft: ViewScale(10),
    borderRadius: ViewScale(8),
    fontSize: ViewScale(16),
    color: '#888888',
    fontFamily: 'Cantoria MT Std',
  },
  iconsea: {
    width: ViewScale(25),
    height: ViewScale(25),
    alignSelf: 'center',
  },
  containersort: {
    flex: 1,
    padding: ViewScale(20),
  },
  viewsort: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: width * 0.9,
    alignSelf: 'center',
  },
  textsort: {
    fontSize: ViewScale(20),
    alignSelf: 'center',
    marginLeft: ViewScale(20),
    fontFamily: 'Cantoria MT Std',
  },
  textsorthead: {
    fontSize: ViewScale(18),
    fontFamily: 'Cantoria MT Std',
    color: '#444444',
  },
  bottomsort: {
    width: ViewScale(20),
    height: ViewScale(20),
    borderRadius: ViewScale(10),
    borderWidth: 1,
    borderColor: '#444',
    marginRight: ViewScale(15),
  },
  textsortdetail: {
    fontSize: ViewScale(18),
    fontFamily: 'Cantoria MT Std',
    color: '#000',
    alignSelf: 'center',
  },
  rowbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: width * 0.85,
    alignSelf: 'center',
    marginVertical: ViewScale(20),
  },
  touch: {
    width: width * 0.4,
    height: ViewScale(35),
    borderColor: '#DAA560',
    borderWidth: 1,
    borderRadius: ViewScale(4),
    justifyContent: 'center',
    alignSelf: 'center',
  },
  textouch: {
    fontSize: ViewScale(20),
    fontFamily: 'Cantoria MT Std',
    color: '#DAA560',
    alignSelf: 'center',
  },
});

export default styles;
