import {Dimensions, Platform, StyleSheet} from 'react-native';
import {ViewScale} from '../../config/ViewScale';
const {width, height} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    width: width,
    height: height,
    backgroundColor: '#000',
  },
  viewsearch: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: ViewScale(15),
    width: width * 0.9,
    alignSelf: 'center',
    marginLeft: ViewScale(10),
    zIndex: 999,
  },
  viewinsearch: {
    flexDirection: 'row',
    width: width * 0.8,
    backgroundColor: '#fff',
    borderRadius: ViewScale(8),
  },
  icon1: {
    alignSelf: 'center',
    marginLeft: ViewScale(10),
    zIndex: 99,
  },
  input: {
    width: ViewScale(320),
    height: Platform.OS === 'ios' ? ViewScale(35) : ViewScale(45),
    marginLeft: ViewScale(10),
    borderRadius: ViewScale(8),
    fontSize: ViewScale(16),
    color: '#888888',
    fontFamily: 'Cantoria MT Std',
  },
  iconsea: {
    width: ViewScale(30),
    height: ViewScale(30),
    alignSelf: 'center',
  },
  containersort: {
    flex: 1,
    padding: ViewScale(20),
  },
  viewsort: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: width * 0.9,
    alignSelf: 'center',
  },
  textsort: {
    fontSize: ViewScale(22),
    alignSelf: 'center',
    marginLeft: ViewScale(20),
    fontFamily: 'Cantoria MT Std',
  },
  textsorthead: {
    fontSize: ViewScale(18),
    fontFamily: 'Cantoria MT Std',
    color: '#444444',
  },
  bottomsort: {
    woidth: ViewScale(20),
    height: ViewScale(20),
    borderRadius: ViewScale(10),
    borderWidth: 1,
    borderColor: '#444',
    marginRight: ViewScale(15),
  },
  textsortdetail: {
    fontSize: ViewScale(18),
    fontFamily: 'Cantoria MT Std',
    color: '#000',
    alignSelf: 'center',
  },
  linersort: {
    width: width * 0.85,
    alignSelf: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#444',
    marginVertical: ViewScale(15),
  },
  bottontags: {
    width: width * 0.4,
    height: ViewScale(40),
    borderWidth: 1,
    borderColor: '#44444450',
    justifyContent: 'center',
    marginTop: ViewScale(10),
    borderRadius: ViewScale(10),
  },
  rowbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: width * 0.85,
    alignSelf: 'center',
    marginVertical: ViewScale(20),
  },
  touch: {
    width: width * 0.4,
    height: ViewScale(35),
    borderColor: '#DAA560',
    borderWidth: 1,
    borderRadius: ViewScale(4),
    justifyContent: 'center',
    alignSelf: 'center',
  },
  textouch: {
    fontSize: ViewScale(20),
    fontFamily: 'Cantoria MT Std',
    color: '#DAA560',
    alignSelf: 'center',
  },
  tags: {
    width: width,
    borderBottomWidth: 1,
    borderBottomColor: '#DAA560',
    paddingLeft: ViewScale(20),
    paddingVertical: ViewScale(20),
  },
  tags1: {
    width: width,

    paddingLeft: ViewScale(20),
    paddingTop: ViewScale(20),
  },
  texttags: {
    fontSize: ViewScale(16),
    color: '#646363',
    fontFamily: 'Cantoria MT Std',
  },
  roww: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: width * 0.9,
    marginBottom: ViewScale(10),
  },
  line: {
    borderBottomWidth: 0.5,
    borderBottomColor: '#DAA560',
  },
  buttonflat: {
    width: width * 0.45,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 2,
    height: ViewScale(210),
    backgroundColor: '#fff',
    borderRadius: 5,
  },
  imgflat: {
    width: width * 0.45,
    height: ViewScale(180),
    alignSelf: 'center',
  },
  text: {
    fontSize: ViewScale(16),
    fontFamily: 'Cantoria MT Std',
    color: '#646363',
    alignSelf: 'center',
    width: width * 0.36,
  },
  imgflat1: {
    width: ViewScale(150),
    height: ViewScale(150),
    alignSelf: 'center',
    justifyContent: 'center',
  },
  imgflat2: {
    width: ViewScale(60),
    height: ViewScale(60),
    alignSelf: 'center',
  },
  text1: {
    fontSize: ViewScale(16),
    fontFamily: 'Cantoria MT Std',
    color: '#646363',
    alignSelf: 'center',
    width: width * 0.35,
    textAlign: 'center',
    marginTop: ViewScale(10),
  },
  iconsea2: {
    width: ViewScale(100),
    height: ViewScale(100),
    alignSelf: 'center',
  },
  com: {
    marginVertical: height * 0.1,
    // borderBottomWidth: 1,
    // borderBottomColor: '#DAA560',
  },
  textccom: {
    fontSize: ViewScale(26),
    color: '#64636350',
    fontFamily: 'Cantoria MT Std',
    alignSelf: 'center',
  },
  imglogo: {
    width: ViewScale(20),
    height: ViewScale(20),
    alignSelf: 'center',
    borderRadius: ViewScale(10),
    borderColor: '#444',
    borderWidth: 0.1,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.43,
    shadowRadius: 9.51,
    elevation: ViewScale(15),
    marginRight: 5,
  },
  row: {
    flexDirection: 'row',
    width: width * 0.4,
    alignSelf: 'center',
    height: ViewScale(30),
  },
});

export default styles;
